# Generated by Django 3.2.5 on 2023-05-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20230506_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='product',
        ),
    ]
